story/urls.py
from django.urls import path, include
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story5.urls')),
]

story5/urls.py
from . import views
from django.shortcuts import render
from django.urls import path

app_name = 'story5'

urlpatterns = [
    path('', views.index, name='index'),
    path('aboutme/', views.aboutme, name='aboutme'),
    path('resume/', views.resume, name='resume'),
    path('gallery/', views.gallery, name='gallery'),
    path('newevent/', views.newevent, name='newevent'),
    path('schedule/', views.listschedule, name='listschedule'),
    path('editschedule/<int:pk>', views.edit, name='edit'),
    path('deleteschedule/<int:pk>', views.delete, name='delete'),
    path('deleteall/', views.deleteall, name='deleteall'),
    path('contact/', views.contact, name='contact'),
]

story5/models.py
from django.db import models
from django.utils import timezone
import datetime

CATEGORY=[('Personal', 'Personal'),
            ('Work', 'Work'),
            ('Quiz', 'Quiz'),
            ('Exam', 'Exam'),
            ('Homework', 'Homework'),
            ('Lab', 'Lab'),
            ('Other', 'Other')]

class Schedule(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    date = models.DateField()
    time = models.TimeField()
    location = models.CharField(max_length=50)
    category = models.CharField(max_length=50, choices=CATEGORY)

story5/forms.py
from django import forms
from .models import Schedule
from django.forms import ModelForm

class ScheduleForm(ModelForm):
    class Meta:
        model= Schedule
        fields = ['name', 'description', 'date', 'time', 'location', 'category']
        labels = {
            'name' : 'Name', 'description' : 'Description', 'date' : 'Date', 'time' : 'Time', 'location' : 'Location', 'category' : 'Category'
        }
        widgets = {
            'name' : forms.TextInput(attrs={'class': 'form-control',
                                        'type' : 'text'}),
            'description' : forms.Textarea(attrs={'class': 'form-control',
                                        'type' : 'textarea', 'rows' : '3'}),
            'date' : forms.DateInput(attrs={'class': 'form-control',
                                        'type' : 'date'}),
            'time' : forms.TimeInput(attrs={'class': 'form-control',
                                        'type' : 'time'}),
            'location' : forms.TextInput(attrs={'class' : 'form-control',
                                        'type' : 'text'}),
            'category' : forms.Select(attrs={'class': 'form-control'})
        }

story5/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .forms import ScheduleForm
from .models import Schedule
import datetime

# Create your views here.
def index(request):
    return render(request, 'index.html')

def aboutme(request):
    return render(request, 'about-me.html')

def resume(request):
    return render(request, 'resume.html')

def gallery(request):
    return render(request, 'gallery.html')

def contact(request):
    return render(request, 'contact.html')

def newevent(request):
    if request.method == 'POST':
        form = ScheduleForm(request.POST)
        if form.is_valid():
                post = form.save(commit=False)
                post.save()
                return redirect('story5:listschedule')
    else:
        form = ScheduleForm()

    content = {'title' : 'Form Schedule',
                'form' : form}

    return render(request, 'schedule_event.html', content)

def listschedule(request):
    data = Schedule.objects.all()
    content = {'title' : 'Schedule',
                'data' : data}
    return render(request, 'schedule.html', content)


def delete(request, pk):
    Schedule.objects.filter(pk=pk).delete()
    data = Schedule.objects.all()
    content = {'title' : 'Schedule',
                'data' : data}
    return redirect('story5:listschedule')

def deleteall(request):
    if request.method == "POST":
        Schedule.objects.all().delete()
        data = Schedule.objects.all()
        content = {'title' : 'Schedule',
                'data' : data}
        return redirect('story5:listschedule')
    else:
        return redirect('story5:listschedule')


def edit(request, pk):
    post = Schedule.objects.get(pk=pk)
    if request.method == "POST":
        form = ScheduleForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('story5:listschedule')
    else:
        form = ScheduleForm(instance=post)

    content = {'title' : 'Form Schedule',
                'form' : form,
                'list' : post}
    return render(request, 'edit_schedule.html', content)

story5/templates/about-me.html
<!DOCTYPE html>
{% load static %}
<html lang="en" style="background-color: #EDDCD2">
    <head>
        <title>Welcome!</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'css/bootstrap/css/bootstrap.min.css' %}">
        <script src="stylesheet" href="{% static 'css/bootstrap/js/bootstrap.min.js' %}"></script>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

        <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
    </head>

    <body>
        <nav class="navbar navbar-expand-md navbar-light fixed-top justifiy-content-end"
        style="background: rgba(240, 227, 219, 0.65);
        box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
        font-family: Averia Regular;
        font-size: 22px;">
        <div class="container-fluid">
            <button type="button" class="navbar-toggler navbar-nav ml-auto" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse text-right" id="navbarCollapse">
                <div class="navbar-nav ml-auto">
                    <a href="{% url 'story5:index' %}" class="nav-item nav-link active" style="color: #454416">home</a>
                    <div class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown" style="color:#454416">
                                about me
                            </a>
                            <div class="dropdown-menu text-right">
                                <a class="dropdown-item" href="#aboutme">about me</a>
                                <a class="dropdown-item" href="#hobbies">hobbies</a>
                            </div>
                    </div>
                    <div class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown" style="color:#454416">
                            resume
                        </a>
                        <div class="dropdown-menu text-right">
                            <a class="dropdown-item" href="{% url 'story5:resume' %}">education</a>
                            <a class="dropdown-item" href="{% url 'story5:resume' %}">experience</a>
                            <a class="dropdown-item" href="{% url 'story5:resume' %}">skill</a>
                        </div>
                    </div>
                    <a href="{% url 'story5:gallery' %}" class="nav-item nav-link" style="color: #454416">gallery</a>
                    <a href="{% url 'story5:listschedule' %}" class="nav-item nav-link" style="color: #454416">schedule</a>
                    <a href="{% url 'story5:contact' %}" class="nav-item nav-link" style="color: #454416">contact</a>
                </div>
            </div>
        </div>    
    </nav>

        <div class="about-me-page">
            <div id="aboutme">
                <div class="row" style="width: auto; height: auto">
                    <div class="col-sm-12 col-md-10 col-lg-10 col-xl-6">
                        <div class="about-me" style="margin-top: 20%">
                            <h1>about me</h1>
                            
                            <p>Inez Amandha (18) is a Computer Science Undergraduate Student at Faculty of Computer Science, Universitas Indonesia.
                                <br><br>
                                Inez loves to travel and go to the aesthetic places. While travelling, she will take some photos (food & places) and share her reviews on social media.
                                <br><br>
                                Currently, she is still learning how to make a website.
                                <br><br>
                                💻 And this is her first-ever website! 💻</p>
                        </div>
                    </div>

                    <div class="col-sm-12 col-md-10 col-lg-10 col-xl-6">
                        <ul class="short-info-box">
                            <li>
                                    <h1>my short info</h1>
                                </li>
                                <li>
                                    <label>Name</label>
                                    <span>Inez Amandha Suci</span>
                                </li>
                                <li>
                                    <label>Age</label>
                                    <span>18</span>
                                </li>
                                <li>
                                    <label>Birthdate</label>
                                    <span>December 21, 2000</span>
                                </li>
                                <li>
                                    <label>Address</label>
                                    <span>Depok, West Java, Indonesia</span>
                                </li>
                                <li>
                                    <label>Education</label>
                                    <span>University of Indonesia</span>
                                </li>
                                <li>
                                    <label>Major</label>
                                    <span>Computer Science (Class of 2018)</span>
                                </li>
                        </ul>
                    </div>
                </div>
            </div>


            <div id="hobbies">
                <div class="row">
                    <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12">
                        <h1 style="margin-left: 7.5%; margin-top: 5%">hobbies</h1>
                        <div id="kotak">
                            <div id="contentBox" style="margin: 0px auto; width:90%; height: auto">
                                <div class="row">
                                    <div class="col-sm-3 col-md-2 col-lg-2 col-xl-2" style="margin: 0px 10px">
                                        <p style="font-family: Poppins-Light; font-size: 14px; color: black">✦ Travelling ✦</p>
                                    </div>

                                    <div class="col-sm-3 col-md-2 col-lg-2 col-xl-2" style="margin: 0px 10px">
                                        <a href="https://www.instagram.com/thefoodsthetic/" target="_blank" style="font-family: Poppins-Light; font-size: 14px">✦ Food & Travel Photography ✦</a>
                                    </div>

                                    <div class="col-sm-3 col-md-2 col-lg-2 col-xl-2" style="margin: 0px 10px">
                                        <p style="font-family: Poppins-Light; font-size: 14px; color: black;">✦ Writing ✦</p>
                                    </div>

                                    <div class="col-sm-3 col-md-2 col-lg-2 col-xl-2" style="margin: 0px 10px">
                                        <p style="font-family: Poppins-Light; font-size: 14px; color: black;">✦ Watching Movies & TV Series ✦</p>
                                    </div>

                                    <div class="col-sm-3 col-md-2 col-lg-2 col-xl-2" style="margin: 0px 10px">
                                        <p style="font-family: Poppins-Light; font-size: 14px; color: black;">✦ Swimming ✦</p>
                                    </div>
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Footer -->
        <footer class="page-footer font-small blue">

        <!-- Copyright -->
        <div class="footer-copyright text-center py-3"
        style="background-color: #B0766B;
        font-family: Poppins-Light;
        font-size: 10px;
        color: white">Copyright © 2019. All Rights Reserved by Inez Amandha
        </div>
        <!-- Copyright -->
      
        </footer>
    </body>

story5/templates/base.html
<!DOCTYPE html>
<html>
    {% load static %}
    <head>
        <title>Welcome!</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'css/bootstrap/css/bootstrap.min.css' %}">
        <script src="stylesheet" href="{% static 'css/bootstrap/js/bootstrap.min.js' %}"></script>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

        <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>

    <body>
        <nav class="navbar navbar-expand-md navbar-light fixed-top justifiy-content-end"
        style="background: rgba(240, 227, 219, 0.65);
        box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
        font-family: Averia Regular;
        font-size: 22px;">
        <div class="container-fluid">
            <button type="button" class="navbar-toggler navbar-nav ml-auto" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse text-right" id="navbarCollapse">
                <div class="navbar-nav ml-auto">
                    <a href="{% url 'story5:index' %}" class="nav-item nav-link active" style="color: #454416">home</a>
                    <div class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown" style="color:#454416">
                                about me
                            </a>
                            <div class="dropdown-menu text-right">
                                <a class="dropdown-item" href="{% url 'story5:aboutme' %}">about me</a>
                                <a class="dropdown-item" href="{% url 'story5:aboutme' %}">hobbies</a>
                            </div>
                    </div>
                    <div class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown" style="color:#454416">
                            resume
                        </a>
                        <div class="dropdown-menu text-right">
                            <a class="dropdown-item" href="{% url 'story5:resume' %}">education</a>
                            <a class="dropdown-item" href="{% url 'story5:resume' %}">experience</a>
                            <a class="dropdown-item" href="{% url 'story5:resume' %}">skill</a>
                        </div>
                    </div>
                    <a href="{% url 'story5:gallery' %}" class="nav-item nav-link" style="color: #454416">gallery</a>
                    <a href="{% url 'story5:listschedule' %}" class="nav-item nav-link" style="color: #454416">schedule</a>
                    <a href="{% url 'story5:contact' %}" class="nav-item nav-link" style="color: #454416">contact</a>
                </div>
            </div>
        </div>    
        </nav>
        {% block content %}
        {% endblock content %}
    </body>
</html>

story5/templates/contact.html
<html lang="en" style="background-color: #EDDCD2">
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="contact-page">
    <div id="contact">
        <h1>contact</h1>
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12">
                <p>
                Hey, there! Let's connect!
                <br>
                Send me a note and tell me about yourself ❤
                </p>
            </div>
        </div>

        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-10 col-md-7 col-lg-6 col-xl-6">
                    <div class="email"
                    style="background-color: #B0766B; border-radius: 25px;
                    padding: 2.5%; margin-left: 7.5%; margin-right: 7.5%; margin-top: 2.5%; margin-bottom: 2.5%">
                        <h3><strong>E-mail:</strong></h3>
                        <h3>inezamandhasuci@gmail.com</h3>
                    </div>
                </div>

                <div class="col-sm-10 col-md-5 col-lg-6 col-xl-6">
                    <h2 style="margin: 5%">I love to connect with you</h2>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-4 col-md-4 col-lg-4 col-xl-4">
                <div class="logo-circle" style="background-color: #E2C7B2">
                    <a href="https://www.instagram.com/inezamandha/">
                        <img src="{% static 'images/photo/logo-instagram.png' %}" style="width: 55px; height: 55px; margin-top: 12.5%;">
                    </a>
                </div>
                <a href="https://www.instagram.com/inezamandha/" style="color: black;">
                    <h4 style=" display: inline-block;">Instagram</h4>
                </a>
            </div>

            <div class="col-sm-4 col-md-4 col-lg-4 col-xl-4">
                <div class="logo-circle" style="background-color: #E7B7A0">
                    <a href="https://twitter.com/inezamandha">
                        <img src="{% static 'images/photo/logo-twitter.png' %}" style="width: 55px; height: 55px; margin-top: 12.5%;">
                    </a>
                </div>
                <a href="https://twitter.com/inezamandha" style="color: black;">
                    <h4 style=" display: inline-block;">Twitter</h4>
                </a>
            </div>
                
            <div class="col-sm-4 col-md-4 col-lg-4 col-xl-4">
                <div class="logo-circle" style="background-color: #CE957A">
                    <a href="https://id.pinterest.com/inezamandha/">
                        <img src="{% static 'images/photo/logo-pinterest.png' %}" style="width: 55px; height: 55px; margin-top: 12.5%;">
                    </a>
                </div>
                <a href="https://id.pinterest.com/inezamandha/" style="color: black;">
                    <h4 style=" display: inline-block;">Pinterest</h4>
                </a>
            </div>
        </div>
    </div>

<!-- Footer -->
<footer class="page-footer font-small blue">

<!-- Copyright -->
<div class="footer-copyright text-center py-3"
style="background-color: #B0766B;
font-family: Poppins-Light;
font-size: 10px;
color: white">Copyright © 2019. All Rights Reserved by Inez Amandha
</div>
<!-- Copyright -->

</footer>
{% endblock %}
</html>

story5/templates/edit_schedule.html
<html lang="en" style="background-color: #CB9A7C">
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="schedule-page">
      <h1 style="width: 50%; margin-top: 0.75em; margin-left: auto; margin-right: auto">Schedule</h1>
      <form style="width: 50%; margin: 0 auto" method="POST" action="{% url 'story5:edit' pk=list.pk %}">
        {% csrf_token %}
        <div class="form-group">
            {{form.name.label_tag}}
            {{form.name}}
          </div>
          <div class="form-group">
            {{form.description.label_tag}}
            {{form.description}}
          </div>
          <div class="form-row">
            <div class="form-group col-md-6">
              {{form.date.label_tag}}
              {{form.date}}
            </div>
            <div class="form-group col-md-6">
              {{form.time.label_tag}}
              {{form.time}}
            </div>
          </div>
          <div class="form-group">
              {{form.location.label_tag}}
              {{form.location}}
            </div>
          <div class="form-group">
              {{form.category.label_tag}}
              {{form.category}}
          </div>

          <button type="submit" class="btn btn-light" style="background-color: #F7EEE5; margin: 2.5% auto; float: left" onclick=history.back()>Back</button>
          <button type="submit" class="btn btn-light" style="background-color: #F7EEE5; margin: 2.5% auto; float: right">Save</button>            
      
        </form>
  </div>    
{% endblock %}
</html>

story5/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div id="home">
    <div class="homepage">
        <div class="row" style="width: 100%; height: auto">
            <div class="col-1 col-sm-1 col-md-1 col-lg-1 col-xl-1" style="margin-top: 40vh">
                <div class="circle-logo" style="background: #E2C7B2; margin-bottom: 10px">
                    <a href="https://www.instagram.com/inezamandha/">
                        <img src="{% static 'images/photo/logo-instagram.png' %}">
                    </a>
                </div>
            
                <div class="circle-logo" style="background: #E7B7A0; margin-bottom: 10px">
                    <a href="https://twitter.com/inezamandha">
                        <img src="{% static 'images/photo/logo-twitter.png' %}">
                    </a>
                </div>

                <div class="circle-logo" style="background: #CE957A">
                    <a href="https://id.pinterest.com/inezamandha/">
                        <img src="{% static 'images/photo/logo-pinterest.png' %}">
                    </a>
                </div>
            </div>
            
            <div class="col-4 col-sm-8 col-md-7 col-lg-7 col-xl-6">
                <img id="profile-photo" src="{% static 'images/photo/profile-photo.jpg' %}" style="margin-bottom: 10vh; margin-right: 25%">
            </div>

            <div class="col-12 col-sm-12 col-md-4 col-lg-4 col-xl-5">
                <div class="homepage-text">
                    <h1>hello, i'm inez!</h1>
                    <h2>❀ welcome to my first website ❀</h2>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Footer -->
<footer class="page-footer font-small blue">

<!-- Copyright -->
<div class="footer-copyright text-center py-3"
style="background-color: #B0766B;
font-family: Poppins-Light;
font-size: 10px;
color: white">Copyright © 2019. All Rights Reserved by Inez Amandha
</div>
<!-- Copyright -->

</footer>
{% endblock %}

story5/templates/schedule.html
<html lang="en" style="background-color: #CB9A7C">
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="list-schedule">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 col-xl-10">
        <h1>Schedule List</h1>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-2 col-lg-2 col-xl-2" style="margin-top: 6%; margin-bottom: 2.5%">
        <a href="{% url 'story5:newevent' %}">
            <button type="submit" class="btn btn-light" style="background-color: #F7EEE5; font-family: Poppins-SemiBold; font-size: 18px; margin-bottom: 2.5%; margin-left: 7.5%">New Event</button>
        </a>
        <form method="POST" action="{% url 'story5:deleteall' %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-icon btn-danger" style="font-family: Poppins-SemiBold; font-size: 18px; margin-left: 7.5%">Delete All</button>
        </form>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="row" style="margin-left: 5%; margin-right: 5%">
          {% for list in data %}
        <div class="col-xs-12 col-sm-9 col-md-9 col-lg-3 col-xl-3" style="background-color: #FFF1E6; border-radius: 15px; padding: 15px; margin: 2.5%; box-shadow: 10px 10px 5px grey;">
            
            <h5 style="font-family: Poppins-SemiBold">{{list.name}}</h5>
            <p style="font-family: Poppins-Light"><i class="fa fa-calendar"></i> {{list.date}} | {{list.time}}</p>
            <p style="font-family: Poppins-Light"><i class="fa fa-map-marker"></i> {{list.location}}</p>
            <p style="font-family: Poppins-Light"><i class="fa fa-th-list"></i> {{list.category}}</p>
            <i class="fa fa-pencil"></i>
            <p style="font-family: Poppins-Light">{{list.description}}</p>

            <a href="{% url 'story5:edit' pk=list.pk %}"><button class="btn btn-icon btn-info" style="background-color: #CE957A">Edit</button></a>
            <a href="{% url 'story5:delete' pk=list.pk %}"><button type="button" class="btn btn-icon btn-danger" style="margin-left: 2.5%">Delete</button></a>
            
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>

<!-- Copyright -->
<div class="footer-copyright text-center py-3"
style="background-color: #B0766B;
font-family: Poppins-Light;
font-size: 10px;
color: white">Copyright © 2019. All Rights Reserved by Inez Amandha
</div>
<!-- Copyright --> 

{% endblock %}
</html>

story5/templates/schedule_event.html
<html lang="en" style="background-color: #CB9A7C">
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="schedule-page">
      <h1 style="width: 50%; margin-top: 0.75em; margin-left: auto; margin-right: auto">Schedule</h1>
      <form style="width: 50%; margin: 0 auto" method="post" action="{% url 'story5:newevent' %}">
        {% csrf_token %}
        <div class="form-group">
            {{form.name.label_tag}}
            {{form.name}}
          </div>
          <div class="form-group">
            {{form.description.label_tag}}
            {{form.description}}
          </div>
          <div class="form-row">
            <div class="form-group col-md-6">
              {{form.date.label_tag}}
              {{form.date}}
            </div>
            <div class="form-group col-md-6">
              {{form.time.label_tag}}
              {{form.time}}
            </div>
          </div>
          <div class="form-group">
              {{form.location.label_tag}}
              {{form.location}}
            </div>
          <div class="form-group">
              {{form.category.label_tag}}
              {{form.category}}
          </div>

          <button type="submit" class="btn btn-light" style="background-color: #F7EEE5; margin: 2.5% auto; float: left" onclick=history.back()>Back</button>
          <button type="submit" class="btn btn-light" style="background-color: #F7EEE5; margin: 2.5% auto; float: right">Add</button>            
      
        </form>
  </div>    
{% endblock %}
</html>